# Keep GitHub Actions and Composer dependencies up to date with GitHub's Dependabot.
# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference
# https://docs.github.com/en/code-security/reference/supply-chain-security/supported-ecosystems-and-repositories
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions:
        patterns:
          - "*" # Group all Actions updates into a single pull request
    schedule:
      interval: weekly

  - package-ecosystem: composer
    directory: /
    groups:
      composer:
        patterns:
          - "*" # Group all Composer updates into a single pull request
    schedule:
      interval: weekly
