<?php

use horstoeko\invoicesuite\InvoiceSuitePdfDocumentBuilder;
use horstoeko\invoicesuite\utils\InvoiceSuiteFileUtils;
use horstoeko\invoicesuite\utils\InvoiceSuitePathUtils;

/**
 * Build a hybrid electronic PDF invoice document by embedding an electronic invoice XML into an existing PDF file
 */

require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/00_ExampleHelpers.php';

$sourceFilesDirectory = InvoiceSuitePathUtils::combineAllPaths(__DIR__, '..', 'tests', 'assets');
$invoiceXmlFilename = InvoiceSuitePathUtils::combinePathWithFile($sourceFilesDirectory, '03_zugferddocumentreader_3.xml');
$sourcePdfFilename = InvoiceSuitePathUtils::combinePathWithFile($sourceFilesDirectory, 'pdf_plain.pdf');
$targetPdfFilename = InvoiceSuitePathUtils::combinePathWithFile(__DIR__, '03_Invoice.pdf');

/*
 * The electronic invoice XML is embedded into an existing PDF file.
 * In a real application this PDF is usually the visual invoice document generated by your ERP/template system.
 */

$pdfBuilder = InvoiceSuitePdfDocumentBuilder::createFromDocumentContentAndPdfFile(
    InvoiceSuiteFileUtils::getContentFromFileOrString($invoiceXmlFilename),
    $sourcePdfFilename
);

$pdfBuilder
    ->setAdditionalCreatorTool('InvoiceSuite example')
    ->setDocumentRelationshipTypeToAlternative()
    ->setAttachmentPaneVisibility(true)
    ->generatePdfDocumentAndSaveToFile($targetPdfFilename);

echo sprintf("Created PDF invoice: %s\n", $targetPdfFilename);
